// TASK-034 · Client Core — GDExtension protocol binding (Godot 4.7.2)
//
// Wraps mmo::protocol::FlatbufCodec (TASK-005) for GDScript consumption.
// Wire decoding deliberately stays in C++ per docs/client-spec-2.5d.md §10
// ("GDExtension(C++) 下沉不变"); GDScript must never re-implement decoding.
//
// Verified against the real TASK-005 headers:
//   mmo::protocol::ICodec::Decode(std::string_view) -> Result<OwnedEnvelope>
//   mmo::protocol::OwnedEnvelope::view()            -> const EnvelopeView&
//   mmo::protocol::EnvelopeView { message_id, message_type(EnvelopeMessageType),
//                                 version, source, timestamp_ms, trace_id,
//                                 request_id, payload, transaction_id, idempotency_key }
//   mmo::core::Result<T>::HasValue() / Value() / Err()
//
// BUILD: requires godot-cpp (4.7.2) + C++17 toolchain + the `protocol` library.
// See README.md in this directory.

#include <cstring>
#include <memory>
#include <string_view>

#include <godot_cpp/classes/engine.hpp>
#include <godot_cpp/core/class_db.hpp>
#include <godot_cpp/godot.hpp>
#include <godot_cpp/variant/array.hpp>
#include <godot_cpp/variant/dictionary.hpp>
#include <godot_cpp/variant/packed_byte_array.hpp>
#include <godot_cpp/variant/string.hpp>
#include <godot_cpp/variant/utility_functions.hpp>

#include <mmo/protocol/codec/flatbuf_codec.h>
#include <mmo/protocol/message_type.h>

#ifdef MMO_PROTOCOL_HAS_AOI_SNAPSHOT
// Generated by: flatc --cpp -I protocol/flatbuffers -I protocol/flatbuffers/schema
//               -o protocol/flatbuffers/generated/cpp protocol/flatbuffers/aoi.fbs
// Schema: AoiBatch { enters:[EntityEnter], leaves:[EntityLeave],
//                    updates:[PositionUpdate], scene_id, timestamp }
#include <aoi_generated.h>
#endif

using namespace godot;

class ProtocolCodec : public Object {
	GDCLASS(ProtocolCodec, Object)

protected:
	static void _bind_methods() {
		ClassDB::bind_method(D_METHOD("decode_envelope", "bytes"), &ProtocolCodec::decode_envelope);
		ClassDB::bind_method(D_METHOD("decode_snapshot", "bytes"), &ProtocolCodec::decode_snapshot);
		ClassDB::bind_method(D_METHOD("encode_envelope", "message_type", "payload"), &ProtocolCodec::encode_envelope);
		ClassDB::bind_method(D_METHOD("encode_test_aoi_batch", "count"), &ProtocolCodec::encode_test_aoi_batch);
	}

public:
	ProtocolCodec() { _codec = std::make_unique<mmo::protocol::FlatbufCodec>(); }

	/// Decode a wire envelope (FlatBuffers) into a Dictionary.
	Dictionary decode_envelope(const PackedByteArray &bytes) const {
		Dictionary out;
		if (bytes.size() == 0) {
			return out;
		}
		std::string_view raw(reinterpret_cast<const char *>(bytes.ptr()), bytes.size());
		auto decoded = _codec->Decode(raw);
		if (!decoded.HasValue()) {
			UtilityFunctions::push_error("ProtocolCodec: envelope decode failed");
			return out;
		}
		const mmo::protocol::EnvelopeView &v = decoded.Value().view();
		out["message_id"] = static_cast<int64_t>(v.message_id);
		out["message_type"] = static_cast<int64_t>(v.message_type);
		out["message_type_name"] = String::utf8(mmo::protocol::ToString(v.message_type));
		out["version"] = static_cast<int64_t>(v.version);
		out["source"] = _to_godot_string(v.source);
		out["timestamp_ms"] = v.timestamp_ms;
		out["trace_id"] = _to_godot_string(v.trace_id);
		out["request_id"] = static_cast<int64_t>(v.request_id);
		out["payload"] = _to_bytes(v.payload);
		out["transaction_id"] = _to_godot_string(v.transaction_id);
		out["idempotency_key"] = _to_godot_string(v.idempotency_key);
		return out;
	}

	/// Decode an AOI/world snapshot.
	///
	/// Returns the envelope fields plus an "entities" Array of
	/// {id, x, y, z} dictionaries consumed by ClientWorld.apply_snapshot().
	///
	/// NOTE: entity extraction requires the AOI FlatBuffers generated header
	/// (currently protocol/flatbuffers/generated/cpp/ has command/common/envelope/
	/// event/query only - `aoi_generated.h` is not yet produced from aoi.fbs).
	/// Until that header exists the array is intentionally left empty so the
	/// binding compiles and the envelope path stays testable; see README.md.
	Dictionary decode_snapshot(const PackedByteArray &bytes) const {
		Dictionary env = decode_envelope(bytes);
		if (env.is_empty()) {
			return env;
		}
		Array entities;
		Array leaves;
#ifdef MMO_PROTOCOL_HAS_AOI_SNAPSHOT
		PackedByteArray payload = env["payload"];
		if (payload.size() == 0) {
			// Nothing to interpret: a snapshot envelope must carry an AoiBatch.
			return Dictionary();
		}
		const uint8_t *pp = payload.ptr();
		flatbuffers::Verifier verifier(pp, static_cast<size_t>(payload.size()));
		if (!mmo::protocol::VerifyAoiBatchBuffer(verifier)) {
			// Corrupt snapshot: drop the frame (ClientWorld keeps the previous one).
			UtilityFunctions::push_error("ProtocolCodec: AOI buffer verification failed - dropping frame");
			return Dictionary();
		}
		auto *batch = mmo::protocol::GetAoiBatch(pp);

		if (batch->enters()) {
			for (flatbuffers::uoffset_t i = 0; i < batch->enters()->size(); ++i) {
				auto *e = batch->enters()->Get(i);
				Dictionary d;
				d["id"] = static_cast<int64_t>(e->entity_id());
				auto *p = e->pos();
				d["x"] = p ? p->x() : 0.0f;
				d["y"] = p ? p->y() : 0.0f;
				d["z"] = p ? p->z() : 0.0f;
				entities.append(d);
			}
		}
		if (batch->updates()) {
			for (flatbuffers::uoffset_t i = 0; i < batch->updates()->size(); ++i) {
				auto *u = batch->updates()->Get(i);
				Dictionary d;
				d["id"] = static_cast<int64_t>(u->entity_id());
				auto *p = u->pos();
				d["x"] = p ? p->x() : 0.0f;
				d["y"] = p ? p->y() : 0.0f;
				d["z"] = p ? p->z() : 0.0f;
				d["rot_y"] = u->rot_y();
				entities.append(d);
			}
		}
		if (batch->leaves()) {
			for (flatbuffers::uoffset_t i = 0; i < batch->leaves()->size(); ++i) {
				leaves.append(static_cast<int64_t>(batch->leaves()->Get(i)->entity_id()));
			}
		}
		env["scene_id"] = static_cast<int64_t>(batch->scene_id());
		env["timestamp"] = batch->timestamp();
#endif
		env["entities"] = entities;
		env["leaves"] = leaves;
		return env;
	}

	/// Encode an envelope around `payload` (message_type = EnvelopeMessageType).
	PackedByteArray encode_envelope(int64_t message_type, const PackedByteArray &payload) const {
		PackedByteArray out;
		mmo::protocol::EnvelopeView v;
		v.message_type = static_cast<mmo::protocol::EnvelopeMessageType>(message_type);
		if (payload.size() > 0) {
			v.payload = std::string_view(reinterpret_cast<const char *>(payload.ptr()), payload.size());
		}
		auto encoded = _codec->Encode(v);
		if (!encoded.HasValue()) {
			UtilityFunctions::push_error("ProtocolCodec: envelope encode failed");
			return out;
		}
		const std::vector<uint8_t> &buf = encoded.Value();
		out.resize(static_cast<int64_t>(buf.size()));
		if (!buf.empty()) {
			std::memcpy(out.ptrw(), buf.data(), buf.size());
		}
		return out;
	}

	/// Test-fixture helper: builds a wire envelope carrying an AoiBatch with
	/// `count` entities. Lets the headless integration test exercise the real
	/// decode path without duplicating FlatBuffers construction in GDScript
	/// (which must never re-implement the protocol).
	PackedByteArray encode_test_aoi_batch(int64_t count) const {
		PackedByteArray out;
#ifdef MMO_PROTOCOL_HAS_AOI_SNAPSHOT
		flatbuffers::FlatBufferBuilder fbb;
		std::vector<flatbuffers::Offset<mmo::protocol::EntityEnter>> enters;
		enters.reserve(static_cast<size_t>(count));
		for (int64_t i = 0; i < count; ++i) {
			// common.fbs declares no namespace, so Vec3 lives in the global one.
			::Vec3 pos(static_cast<float>(i), 0.0f, static_cast<float>(i));
			enters.push_back(mmo::protocol::CreateEntityEnter(
				fbb, static_cast<uint64_t>(i + 1), 1, &pos, 1));
		}
		auto enters_vec = fbb.CreateVector(enters);
		auto batch = mmo::protocol::CreateAoiBatch(fbb, enters_vec, 0, 0, 1, 1234567890);
		fbb.Finish(batch, mmo::protocol::AoiBatchIdentifier());

		mmo::protocol::EnvelopeView v;
		v.message_type = mmo::protocol::EnvelopeMessageType::Event;
		v.payload = std::string_view(
			reinterpret_cast<const char *>(fbb.GetBufferPointer()), fbb.GetSize());
		auto encoded = _codec->Encode(v);
		if (!encoded.HasValue()) {
			UtilityFunctions::push_error("ProtocolCodec: test AoiBatch encode failed");
			return out;
		}
		const std::vector<uint8_t> &buf = encoded.Value();
		out.resize(static_cast<int64_t>(buf.size()));
		if (!buf.empty()) {
			std::memcpy(out.ptrw(), buf.data(), buf.size());
		}
#else
		UtilityFunctions::push_warning(
			"ProtocolCodec: encode_test_aoi_batch needs MMO_PROTOCOL_HAS_AOI_SNAPSHOT (scons aoi_snapshot=1)");
#endif
		return out;
	}

private:
	static String _to_godot_string(std::string_view sv) {
		return String::utf8(sv.data(), static_cast<int64_t>(sv.size()));
	}

	static PackedByteArray _to_bytes(std::string_view sv) {
		PackedByteArray out;
		out.resize(static_cast<int64_t>(sv.size()));
		if (!sv.empty()) {
			std::memcpy(out.ptrw(), sv.data(), sv.size());
		}
		return out;
	}

	std::unique_ptr<mmo::protocol::FlatbufCodec> _codec;
};

static ProtocolCodec *g_protocol_codec_singleton = nullptr;

void initialize_protocol_codec_module(ModuleInitializationLevel p_level) {
	if (p_level != MODULE_INITIALIZATION_LEVEL_SCENE) {
		return;
	}
	ClassDB::register_internal_class<ProtocolCodec>();
	g_protocol_codec_singleton = memnew(ProtocolCodec);
	Engine::get_singleton()->register_singleton("ProtocolCodec", g_protocol_codec_singleton);
}

void uninitialize_protocol_codec_module(ModuleInitializationLevel p_level) {
	if (p_level != MODULE_INITIALIZATION_LEVEL_SCENE) {
		return;
	}
	if (g_protocol_codec_singleton != nullptr) {
		Engine::get_singleton()->unregister_singleton("ProtocolCodec");
		memdelete(g_protocol_codec_singleton);
		g_protocol_codec_singleton = nullptr;
	}
}

extern "C" {
// Entry point referenced by protocol_codec.gdextension.
GDExtensionBool GDE_EXPORT protocol_codec_init(
		GDExtensionInterfaceGetProcAddress p_get_proc_address,
		const GDExtensionClassLibraryPtr p_library,
		GDExtensionInitialization *r_initialization) {
	GDExtensionBinding::InitObject init_obj(p_get_proc_address, p_library, r_initialization);
	init_obj.register_initializer(initialize_protocol_codec_module);
	init_obj.register_terminator(uninitialize_protocol_codec_module);
	init_obj.set_minimum_library_initialization_level(MODULE_INITIALIZATION_LEVEL_SCENE);
	return init_obj.init();
}
}
