# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: config_skills.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'config_skills.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63onfig_skills.proto\x12\x0b\x43\x41MI.Config\x1a\x0c\x63ommon.proto\"\xa8\x04\n\x0bSkillConfig\x12\x10\n\x08skill_id\x18\x01 \x01(\r\x12\x10\n\x08name_key\x18\x02 \x01(\t\x12\x17\n\x0f\x64\x65scription_key\x18\x03 \x01(\t\x12*\n\nskill_type\x18\x04 \x01(\x0e\x32\x16.CAMI.Config.SkillType\x12,\n\x0b\x64\x61mage_type\x18\x05 \x01(\x0e\x32\x17.CAMI.Common.DamageType\x12,\n\x0btarget_type\x18\x06 \x01(\x0e\x32\x17.CAMI.Config.TargetType\x12\x13\n\x0b\x63ooldown_ms\x18\x07 \x01(\r\x12\x14\n\x0c\x63\x61st_time_ms\x18\x08 \x01(\r\x12\x0e\n\x06gcd_ms\x18\t \x01(\r\x12\x11\n\tmana_cost\x18\n \x01(\x05\x12\r\n\x05range\x18\x0b \x01(\x02\x12\x0e\n\x06radius\x18\x0c \x01(\x02\x12\x13\n\x0bmax_targets\x18\r \x01(\r\x12\x12\n\nbase_value\x18\x0e \x01(\x05\x12\x13\n\x0b\x63oefficient\x18\x0f \x01(\x02\x12+\n\x0cscaling_stat\x18\x10 \x01(\x0e\x32\x15.CAMI.Common.StatType\x12*\n\x07\x65\x66\x66\x65\x63ts\x18\x11 \x03(\x0b\x32\x19.CAMI.Common.EffectConfig\x12.\n\x0erequired_class\x18\x12 \x03(\x0e\x32\x16.CAMI.Common.ClassType\x12\x12\n\nscript_ref\x18\x13 \x01(\t\x12\x0c\n\x04icon\x18\x14 \x01(\t\"P\n\x0eSkillConfigSet\x12\x14\n\x0c\x64\x61ta_version\x18\x01 \x01(\r\x12(\n\x06skills\x18\x02 \x03(\x0b\x32\x18.CAMI.Config.SkillConfig*\x9b\x01\n\tSkillType\x12\x11\n\rSKILL_UNKNOWN\x10\x00\x12\x10\n\x0cSKILL_ATTACK\x10\x01\x12\x0e\n\nSKILL_HEAL\x10\x02\x12\x0e\n\nSKILL_BUFF\x10\x03\x12\x10\n\x0cSKILL_DEBUFF\x10\x04\x12\x10\n\x0cSKILL_SUMMON\x10\x05\x12\x12\n\x0eSKILL_TELEPORT\x10\x06\x12\x11\n\rSKILL_PASSIVE\x10\x07*w\n\nTargetType\x12\x0f\n\x0bTARGET_NONE\x10\x00\x12\x0f\n\x0bTARGET_SELF\x10\x01\x12\x10\n\x0cTARGET_ENEMY\x10\x02\x12\x13\n\x0fTARGET_FRIENDLY\x10\x03\x12\x10\n\x0cTARGET_POINT\x10\x04\x12\x0e\n\nTARGET_AOE\x10\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'config_skills_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SKILLTYPE']._serialized_start=688
  _globals['_SKILLTYPE']._serialized_end=843
  _globals['_TARGETTYPE']._serialized_start=845
  _globals['_TARGETTYPE']._serialized_end=964
  _globals['_SKILLCONFIG']._serialized_start=51
  _globals['_SKILLCONFIG']._serialized_end=603
  _globals['_SKILLCONFIGSET']._serialized_start=605
  _globals['_SKILLCONFIGSET']._serialized_end=685
# @@protoc_insertion_point(module_scope)
