# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: config_stats.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'config_stats.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2
import config_items_pb2 as config__items__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63onfig_stats.proto\x12\x0b\x43\x41MI.Config\x1a\x0c\x63ommon.proto\x1a\x12\x63onfig_items.proto\"g\n\x15RatingConversionPoint\x12\r\n\x05level\x18\x01 \x01(\r\x12#\n\x04stat\x18\x02 \x01(\x0e\x32\x15.CAMI.Common.StatType\x12\x1a\n\x12rating_per_percent\x18\x03 \x01(\x02\"\xc3\x01\n\x11ItemizationBudget\x12\x12\n\nitem_level\x18\x01 \x01(\r\x12)\n\x07quality\x18\x02 \x01(\x0e\x32\x18.CAMI.Config.ItemQuality\x12$\n\x04slot\x18\x03 \x01(\x0e\x32\x16.CAMI.Config.EquipSlot\x12\x16\n\x0eprimary_budget\x18\x04 \x01(\r\x12\x18\n\x10secondary_budget\x18\x05 \x01(\r\x12\x17\n\x0ftertiary_chance\x18\x06 \x01(\x02\"d\n\x0f\x43lassStatWeight\x12%\n\x05\x63lass\x18\x01 \x01(\x0e\x32\x16.CAMI.Common.ClassType\x12*\n\x07weights\x18\x02 \x03(\x0b\x32\x19.CAMI.Common.StatModifier\"|\n\x0f\x44\x65rivedStatRule\x12)\n\ninput_stat\x18\x01 \x01(\x0e\x32\x15.CAMI.Common.StatType\x12*\n\x0boutput_stat\x18\x02 \x01(\x0e\x32\x15.CAMI.Common.StatType\x12\x12\n\nconversion\x18\x03 \x01(\x02\"\xfa\x01\n\rStatConfigSet\x12\x14\n\x0c\x64\x61ta_version\x18\x01 \x01(\r\x12\x38\n\x0crating_curve\x18\x02 \x03(\x0b\x32\".CAMI.Config.RatingConversionPoint\x12/\n\x07\x62udgets\x18\x03 \x03(\x0b\x32\x1e.CAMI.Config.ItemizationBudget\x12\x33\n\rclass_weights\x18\x04 \x03(\x0b\x32\x1c.CAMI.Config.ClassStatWeight\x12\x33\n\rderived_rules\x18\x05 \x03(\x0b\x32\x1c.CAMI.Config.DerivedStatRuleb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'config_stats_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RATINGCONVERSIONPOINT']._serialized_start=69
  _globals['_RATINGCONVERSIONPOINT']._serialized_end=172
  _globals['_ITEMIZATIONBUDGET']._serialized_start=175
  _globals['_ITEMIZATIONBUDGET']._serialized_end=370
  _globals['_CLASSSTATWEIGHT']._serialized_start=372
  _globals['_CLASSSTATWEIGHT']._serialized_end=472
  _globals['_DERIVEDSTATRULE']._serialized_start=474
  _globals['_DERIVEDSTATRULE']._serialized_end=598
  _globals['_STATCONFIGSET']._serialized_start=601
  _globals['_STATCONFIGSET']._serialized_end=851
# @@protoc_insertion_point(module_scope)
