# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: config_world_events.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'config_world_events.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x63onfig_world_events.proto\x12\x0b\x43\x41MI.Config\x1a\x0c\x63ommon.proto\"\x85\x01\n\x0cScheduleRule\x12\x12\n\nstart_date\x18\x01 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x02 \x01(\t\x12\x12\n\nstart_hour\x18\x03 \x01(\r\x12\x16\n\x0e\x64uration_hours\x18\x04 \x01(\r\x12\x12\n\nrecurrence\x18\x05 \x01(\r\x12\x0f\n\x07weekday\x18\x06 \x01(\r\"e\n\x11WorldEventBalance\x12\"\n\x1a\x65xpected_currency_per_hour\x18\x01 \x01(\x02\x12\x15\n\rtolerance_pct\x18\x02 \x01(\x02\x12\x15\n\ralert_channel\x18\x03 \x01(\t\"\xe4\x02\n\x10WorldEventConfig\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\r\x12\x10\n\x08name_key\x18\x02 \x01(\t\x12\x31\n\x08\x63\x61tegory\x18\x03 \x01(\x0e\x32\x1f.CAMI.Config.WorldEventCategory\x12+\n\x08schedule\x18\x04 \x01(\x0b\x32\x19.CAMI.Config.ScheduleRule\x12\x19\n\x11\x61\x66\x66\x65\x63ted_zone_ids\x18\x05 \x03(\r\x12\x11\n\tquest_ids\x18\x06 \x03(\r\x12\x14\n\x0c\x63reature_ids\x18\x07 \x03(\r\x12\x19\n\x11\x65vent_currency_id\x18\x08 \x01(\r\x12(\n\x07rewards\x18\t \x03(\x0b\x32\x17.CAMI.Common.ItemReward\x12\x12\n\nscript_ref\x18\n \x01(\t\x12/\n\x07\x62\x61lance\x18\x0b \x01(\x0b\x32\x1e.CAMI.Config.WorldEventBalance\"Z\n\x13WorldEventConfigSet\x12\x14\n\x0c\x64\x61ta_version\x18\x01 \x01(\r\x12-\n\x06\x65vents\x18\x02 \x03(\x0b\x32\x1d.CAMI.Config.WorldEventConfig*p\n\x12WorldEventCategory\x12\x0e\n\nEVENT_NONE\x10\x00\x12\x11\n\rEVENT_HOLIDAY\x10\x01\x12\x0f\n\x0b\x45VENT_WORLD\x10\x02\x12\x12\n\x0e\x45VENT_INVASION\x10\x03\x12\x12\n\x0e\x45VENT_SCENARIO\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'config_world_events_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WORLDEVENTCATEGORY']._serialized_start=746
  _globals['_WORLDEVENTCATEGORY']._serialized_end=858
  _globals['_SCHEDULERULE']._serialized_start=57
  _globals['_SCHEDULERULE']._serialized_end=190
  _globals['_WORLDEVENTBALANCE']._serialized_start=192
  _globals['_WORLDEVENTBALANCE']._serialized_end=293
  _globals['_WORLDEVENTCONFIG']._serialized_start=296
  _globals['_WORLDEVENTCONFIG']._serialized_end=652
  _globals['_WORLDEVENTCONFIGSET']._serialized_start=654
  _globals['_WORLDEVENTCONFIGSET']._serialized_end=744
# @@protoc_insertion_point(module_scope)
