# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: config_spawns.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'config_spawns.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63onfig_spawns.proto\x12\x0b\x43\x41MI.Config\x1a\x0c\x63ommon.proto\"\xa5\x01\n\x0eSpawnCondition\x12\x11\n\tmin_level\x18\x01 \x01(\r\x12\x11\n\tmax_level\x18\x02 \x01(\r\x12\x1f\n\x17required_phase_group_id\x18\x03 \x01(\r\x12\x1a\n\x12required_event_ids\x18\x04 \x03(\r\x12\x17\n\x0ftime_of_day_min\x18\x05 \x01(\r\x12\x17\n\x0ftime_of_day_max\x18\x06 \x01(\r\"\x86\x02\n\nSpawnEntry\x12\x10\n\x08spawn_id\x18\x01 \x01(\r\x12\x0f\n\x07zone_id\x18\x02 \x01(\r\x12\x1c\n\x14\x63reature_template_id\x18\x03 \x01(\r\x12#\n\x08position\x18\x04 \x01(\x0b\x32\x11.CAMI.Common.Vec3\x12\x15\n\rwander_radius\x18\x05 \x01(\x02\x12\x13\n\x0brespawn_sec\x18\x06 \x01(\r\x12\x11\n\tmax_alive\x18\x07 \x01(\r\x12\x12\n\ngroup_size\x18\x08 \x01(\r\x12.\n\tcondition\x18\t \x01(\x0b\x32\x1b.CAMI.Config.SpawnCondition\x12\x0f\n\x07pool_id\x18\n \x01(\r\"2\n\x0eSpawnPoolEntry\x12\x10\n\x08spawn_id\x18\x01 \x01(\r\x12\x0e\n\x06weight\x18\x02 \x01(\r\"p\n\tSpawnPool\x12\x0f\n\x07pool_id\x18\x01 \x01(\r\x12\x10\n\x08name_key\x18\x02 \x01(\t\x12\x12\n\nmax_active\x18\x03 \x01(\r\x12,\n\x07\x65ntries\x18\x04 \x03(\x0b\x32\x1b.CAMI.Config.SpawnPoolEntry\"z\n\x13SpawnDensityBalance\x12\x0f\n\x07zone_id\x18\x01 \x01(\r\x12$\n\x1ctarget_kills_per_player_hour\x18\x02 \x01(\x02\x12\x15\n\rtolerance_pct\x18\x03 \x01(\x02\x12\x15\n\ralert_channel\x18\x04 \x01(\t\"\xa9\x01\n\x0eSpawnConfigSet\x12\x14\n\x0c\x64\x61ta_version\x18\x01 \x01(\r\x12\'\n\x06spawns\x18\x02 \x03(\x0b\x32\x17.CAMI.Config.SpawnEntry\x12%\n\x05pools\x18\x03 \x03(\x0b\x32\x16.CAMI.Config.SpawnPool\x12\x31\n\x07\x64\x65nsity\x18\x04 \x03(\x0b\x32 .CAMI.Config.SpawnDensityBalanceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'config_spawns_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SPAWNCONDITION']._serialized_start=51
  _globals['_SPAWNCONDITION']._serialized_end=216
  _globals['_SPAWNENTRY']._serialized_start=219
  _globals['_SPAWNENTRY']._serialized_end=481
  _globals['_SPAWNPOOLENTRY']._serialized_start=483
  _globals['_SPAWNPOOLENTRY']._serialized_end=533
  _globals['_SPAWNPOOL']._serialized_start=535
  _globals['_SPAWNPOOL']._serialized_end=647
  _globals['_SPAWNDENSITYBALANCE']._serialized_start=649
  _globals['_SPAWNDENSITYBALANCE']._serialized_end=771
  _globals['_SPAWNCONFIGSET']._serialized_start=774
  _globals['_SPAWNCONFIGSET']._serialized_end=943
# @@protoc_insertion_point(module_scope)
