# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: config_loot.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'config_loot.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import config_items_pb2 as config__items__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63onfig_loot.proto\x12\x0b\x43\x41MI.Config\x1a\x12\x63onfig_items.proto\"s\n\rLootItemEntry\x12\x0f\n\x07item_id\x18\x01 \x01(\r\x12\x0e\n\x06weight\x18\x02 \x01(\r\x12-\n\x0bmin_quality\x18\x03 \x01(\x0e\x32\x18.CAMI.Config.ItemQuality\x12\x12\n\nchance_pct\x18\x04 \x01(\r\"\xb1\x02\n\tLootTable\x12\x15\n\rloot_table_id\x18\x01 \x01(\r\x12\x10\n\x08name_key\x18\x02 \x01(\t\x12+\n\x07\x65ntries\x18\x03 \x03(\x0b\x32\x1a.CAMI.Config.LootItemEntry\x12\x16\n\x0e\x64rop_count_min\x18\x04 \x01(\r\x12\x16\n\x0e\x64rop_count_max\x18\x05 \x01(\r\x12\x1b\n\x13max_drops_per_actor\x18\x06 \x01(\r\x12-\n\x0bquality_cap\x18\x07 \x01(\x0e\x32\x18.CAMI.Config.ItemQuality\x12\x19\n\x11\x62onus_roll_chance\x18\x08 \x01(\x02\x12\x37\n\x15\x65xpected_quality_dist\x18\t \x03(\x0e\x32\x18.CAMI.Config.ItemQuality\"\x82\x01\n\x08LootRule\x12\x0f\n\x07rule_id\x18\x01 \x01(\r\x12/\n\x04mode\x18\x02 \x01(\x0e\x32!.CAMI.Config.LootDistributionMode\x12\x1d\n\x15personal_cooldown_sec\x18\x03 \x01(\r\x12\x15\n\rattempt_limit\x18\x04 \x01(\r\"r\n\x0cLootTableSet\x12\x14\n\x0c\x64\x61ta_version\x18\x01 \x01(\r\x12&\n\x06tables\x18\x02 \x03(\x0b\x32\x16.CAMI.Config.LootTable\x12$\n\x05rules\x18\x03 \x03(\x0b\x32\x15.CAMI.Config.LootRule*\x8a\x01\n\x14LootDistributionMode\x12\x15\n\x11LOOT_FREE_FOR_ALL\x10\x00\x12\x14\n\x10LOOT_ROUND_ROBIN\x10\x01\x12\x14\n\x10LOOT_MASTER_LOOT\x10\x02\x12\x13\n\x0fLOOT_GROUP_LOOT\x10\x03\x12\x1a\n\x16LOOT_NEED_BEFORE_GREED\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'config_loot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOOTDISTRIBUTIONMODE']._serialized_start=729
  _globals['_LOOTDISTRIBUTIONMODE']._serialized_end=867
  _globals['_LOOTITEMENTRY']._serialized_start=54
  _globals['_LOOTITEMENTRY']._serialized_end=169
  _globals['_LOOTTABLE']._serialized_start=172
  _globals['_LOOTTABLE']._serialized_end=477
  _globals['_LOOTRULE']._serialized_start=480
  _globals['_LOOTRULE']._serialized_end=610
  _globals['_LOOTTABLESET']._serialized_start=612
  _globals['_LOOTTABLESET']._serialized_end=726
# @@protoc_insertion_point(module_scope)
