# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cross_server.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'cross_server.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63ross_server.proto\x12\x10\x43\x41MI.CrossServer\x1a\x0c\x63ommon.proto\"\xf2\x01\n\x10\x43rossServerEvent\x12\x10\n\x08realm_id\x18\x01 \x01(\t\x12\x10\n\x08\x65vent_id\x18\x02 \x01(\x04\x12\x11\n\tserver_ts\x18\x03 \x01(\x03\x12+\n\x04\x63hat\x18\n \x01(\x0b\x32\x1b.CAMI.CrossServer.CrossChatH\x00\x12\x33\n\x06\x62\x61ttle\x18\x0b \x01(\x0b\x32!.CAMI.CrossServer.CrossBattleSyncH\x00\x12:\n\x0cguild_invite\x18\x0c \x01(\x0b\x32\".CAMI.CrossServer.CrossGuildInviteH\x00\x42\t\n\x07payload\"?\n\tCrossChat\x12\x13\n\x0b\x66rom_player\x18\x01 \x01(\x04\x12\x0f\n\x07\x63hannel\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\"n\n\x0f\x43rossBattleSync\x12\x0f\n\x07zone_id\x18\x01 \x01(\x04\x12\x13\n\x0bparticipant\x18\x02 \x03(\x04\x12\r\n\x05phase\x18\x03 \x01(\x05\x12&\n\x0brally_point\x18\x04 \x01(\x0b\x32\x11.CAMI.Common.Vec3\"F\n\x10\x43rossGuildInvite\x12\x10\n\x08guild_id\x18\x01 \x01(\x04\x12\x0f\n\x07inviter\x18\x02 \x01(\x04\x12\x0f\n\x07invitee\x18\x03 \x01(\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cross_server_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CROSSSERVEREVENT']._serialized_start=55
  _globals['_CROSSSERVEREVENT']._serialized_end=297
  _globals['_CROSSCHAT']._serialized_start=299
  _globals['_CROSSCHAT']._serialized_end=362
  _globals['_CROSSBATTLESYNC']._serialized_start=364
  _globals['_CROSSBATTLESYNC']._serialized_end=474
  _globals['_CROSSGUILDINVITE']._serialized_start=476
  _globals['_CROSSGUILDINVITE']._serialized_end=546
# @@protoc_insertion_point(module_scope)
